{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lndmon.fullname" . }}
  labels:
    {{- include "lndmon.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "lndmon.selectorLabels" . | nindent 4 }}
{{- end }}
