cert-manager:
  enabled: false
kubemonkey:
  enabled: false
opentelemetry-collector:
  enabled: false
strimzi-kafka-operator:
  enabled: false
ingress-nginx:
  controller:
    allowSnippetAnnotations: true
    admissionWebhooks:
      enabled: false
    config:
      enable-opentelemetry: "true"
      otlp-collector-host: opentelemetry-collector.galoy-dev-otel.svc.cluster.local
      otlp-collector-port: "4317"
      otel-service-name: galoy-dev-ingress
    service:
      type: NodePort
