cert-manager:
  enabled: false
kubemonkey:
  enabled: false
opentelemetry-collector:
  enabled: false
strimzi-kafka-operator:
  enabled: false
ingress-nginx:
  controller:
    allowSnippetAnnotations: true
    admissionWebhooks:
      enabled: false
    service:
      type: NodePort
