{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-backup" (include "lnd.fullname" .) }}
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
data:
  backup.sh: |
    #!/bin/sh
    set -e

    echo "Starting LND SCB backup service..."

    # Set environment variables for the Node.js service
    {{- if .Values.backup.gcs.enabled }}
    export GCS_ENABLED=true
    export GCS_BUCKET={{ .Values.backup.gcs.bucketName }}
    {{- else }}
    export GCS_ENABLED=false
    {{- end }}

    {{- if .Values.backup.s3.enabled }}
    export S3_ENABLED=true
    export S3_BUCKET={{ .Values.backup.s3.bucketName }}
    {{- else }}
    export S3_ENABLED=false
    {{- end }}

    {{- if .Values.backup.nextcloud.enabled }}
    export NEXTCLOUD_ENABLED=true
    export NEXTCLOUD_URL={{ .Values.backup.nextcloud.url }}
    {{- else }}
    export NEXTCLOUD_ENABLED=false
    {{- end }}

    # Start the Node.js backup service
    echo "Starting Node.js backup service..."
    exec node /app/backup-service.js
{{- end }}
