global:
  network: regtest

resources:
  limits:
    cpu: 200m
    memory: 512Mi

terminationGracePeriodSeconds: 0

persistence:
  enabled: false

# Enable backup for development testing
backup:
  enabled: true
  s3:
    enabled: true
    bucketName: "lnd-backup-bucket"
    region: "us-east-1"
    accessKeySecret:
      name: "minio-credentials"
      key: "access-key-id"
    secretKeySecret:
      name: "minio-credentials"
      key: "secret-access-key"

configmap:
  customValues:
  - bitcoin.regtest=true
  - bitcoin.defaultchanconfs=0
  - noseedbackup=1
  - bitcoind.rpchost=bitcoind:18443
  - keysend-hold-time=2s
  - tlsextradomain=lnd1.galoy-dev-bitcoin.svc.cluster.local
