global:
  network: regtest

resources:
  limits:
    cpu: 200m
    memory: 512Mi

terminationGracePeriodSeconds: 0

persistence:
  enabled: false

configmap:
  customValues:
  - bitcoin.regtest=true
  - bitcoin.defaultchanconfs=0
  - noseedbackup=1
  - bitcoind.rpchost=bitcoind:18443
  - keysend-hold-time=2s
  - tlsextradomain=lnd1.galoy-dev-bitcoin.svc.cluster.local
  - rpcmiddleware.enable=true # Enable RPC middleware for Lightning Terminal

# Enable PostgreSQL backend
postgresql:
  enabled: true
  auth:
    enablePostgresUser: false
    username: lnd
    password: lnd
    database: lnd
    existingSecret: lnd-postgres-creds
  primary:
    persistence:
      enabled: false

lnd:
  db:
    backend: postgres
    config:
      secret: lnd-postgres-creds
      postgres:
        timeout: 0
        maxconnections: 21

# Enable backup for development testing
backupImage:
  repository: us.gcr.io/galoy-org/lnd-backup
backup:
  enabled: true
  s3:
    enabled: true
    bucketName: "lnd-backup-bucket"
    region: "us-east-1"
    accessKeySecret:
      name: "minio-credentials"
      key: "access-key-id"
    secretKeySecret:
      name: "minio-credentials"
      key: "secret-access-key"

# Enable lndmon subchart for development monitoring
lndmon:
  enabled: true

# Enable Lightning Terminal subchart for development
lightning-terminal:
  enabled: true
  lit:
    # Development password - NOT for production
    uiPassword: "devpassword123"
  autopilot:
    # Enable autopilot for development testing
    enabled: true
  # Disable persistence for regtest to avoid macaroon unlock issues
  persistence:
    enabled: false
