global:
  network: regtest

resources:
  limits:
    cpu: 200m
    memory: 512Mi

terminationGracePeriodSeconds: 0

persistence:
  enabled: false

configmap:
  customValues:
  - bitcoin.regtest=true
  - bitcoin.defaultchanconfs=0
  - noseedbackup=1
  - bitcoind.rpchost=bitcoind:18443
  - keysend-hold-time=2s
  - tlsextradomain=lnd1.galoy-dev-bitcoin.svc.cluster.local

# Enable PostgreSQL backend
postgresql:
  enabled: true
  auth:
    enablePostgresUser: false
    username: lnd
    password: lnd
    database: lnd
    existingSecret: lnd-postgres-creds
  primary:
    persistence:
      enabled: false

lnd:
  db:
    backend: postgres
    config:
      secret: lnd-postgres-creds
      postgres:
        timeout: 0
        maxconnections: 21
