global:
  network: regtest

resources:
  limits:
    cpu: 200m
    memory: 512Mi

terminationGracePeriodSeconds: 0

persistence:
  enabled: false

# Use different ports to avoid conflicts with lnd1
apiService:
  ports:
    rpc: 10010
    rest: 8081

p2pService:
  port: 9736

configmap:
  customValues:
  - bitcoin.regtest=true
  - bitcoin.defaultchanconfs=0
  - noseedbackup=1
  - bitcoind.rpchost=bitcoind:18443
  - keysend-hold-time=2s
  - tlsextradomain=lnd2.galoy-dev-bitcoin.svc.cluster.local
