image:
  repository: us.gcr.io/galoy-org/galoy-admin-panel
  digest: "sha256:1c15741140622c2c2c423d6ed0afec0a3e142562357ae23483187ebeba6fd885" # METADATA:: repository=https://github.com/blinkbitcoin/blink;commit_ref=90a55d8;app=admin-panel;monorepo_subdir=apps/admin-panel;
  git_ref: "ef99dc0" # Not used by helm
ingress:
  enabled: false
service:
  port: 3000
  type: ClusterIP
adminPanel:
  adminCoreApi: http://admin-api.galoy-dev-galoy.svc.cluster.local:4001/admin/graphql
  nextAuthUrl: http://localhost:3000
  authorizedEmails: "satoshi@blink.sv,nakamoto@blink.sv"
  userRoleMap: {}
resources: {}
secrets:
  create: true
  googleOauthClientId: ""
  googleOauthClientSecret: ""
  nextAuthSecret: ""
otelExporterOtlpEndpoint: http://localhost:4318
tracingServiceName: "admin-panel"
