image:
  repository: us.gcr.io/galoy-org/galoy-admin-panel
  digest: "sha256:39ac5eeed55bf7b2830f654b85195d68454b58d4082e91224c173f338ac282a2" # METADATA:: repository=https://github.com/blinkbitcoin/blink;commit_ref=3f54ac8;app=admin-panel;monorepo_subdir=apps/admin-panel;
  git_ref: "ef99dc0" # Not used by helm
ingress:
  enabled: false
service:
  port: 3000
  type: ClusterIP
adminPanel:
  adminCoreApi: http://admin-api.galoy-dev-galoy.svc.cluster.local:4001/admin/graphql
  nextAuthUrl: http://localhost:3000
  authorizedEmails: "satoshi@blink.sv,nakamoto@blink.sv"
  userRoleMap: {}
resources: {}
secrets:
  create: true
  googleOauthClientId: ""
  googleOauthClientSecret: ""
  nextAuthSecret: ""
otelExporterOtlpEndpoint: http://localhost:4318
tracingServiceName: "admin-panel"
