image:
  repository: us.gcr.io/galoy-org/galoy-admin-panel
  digest: "sha256:8e7e3b038b95941cc7fbeb23e5327f9a40f92bbaf66e8a4af60e08d7ffeb168a" # METADATA:: repository=https://github.com/blinkbitcoin/blink;commit_ref=85f1178;app=admin-panel;monorepo_subdir=apps/admin-panel;
  git_ref: "ef99dc0" # Not used by helm
ingress:
  enabled: false
service:
  port: 3000
  type: ClusterIP
adminPanel:
  adminCoreApi: http://admin-api.galoy-dev-galoy.svc.cluster.local:4001/admin/graphql
  nextAuthUrl: http://localhost:3000
  authorizedEmails: "satoshi@blink.sv,nakamoto@blink.sv"
  userRoleMap: {}
resources: {}
secrets:
  create: true
  googleOauthClientId: ""
  googleOauthClientSecret: ""
  nextAuthSecret: ""
otelExporterOtlpEndpoint: http://localhost:4318
tracingServiceName: "admin-panel"
