secrets:
  create: true
  mapApiKey: ""
map:
  coreUrl: "http://galoy-oathkeeper-proxy.galoy-dev-galoy.svc.cluster.local:4455/graphql"
  otelExporterOtlpEndpoint: http://localhost:4318
  tracingServiceName: "map"
image:
  repository: us.gcr.io/galoy-org/galoy-map
  digest: "sha256:05df566e78a58c00a667098feed15dd16fcdce4732cc7b96a36e5bdd2d6e31de" # METADATA:: repository=https://github.com/blinkbitcoin/blink;commit_ref=3e7cab2;app=map;monorepo_subdir=apps/map;
ingress:
  enabled: false
service:
  port: 3000
  type: ClusterIP
resources: {}
