secrets:
  create: true
  mapApiKey: ""
map:
  coreUrl: "http://galoy-oathkeeper-proxy.galoy-dev-galoy.svc.cluster.local:4455/graphql"
  otelExporterOtlpEndpoint: http://localhost:4318
  tracingServiceName: "map"
image:
  repository: us.gcr.io/galoy-org/galoy-map
  digest: "sha256:64b57f6fb4f824a3bdd0d7fb2eeb14339e7da948fdfaa8486f3f3a16977e19e0" # METADATA:: repository=https://github.com/blinkbitcoin/blink;commit_ref=e780b5d;app=map;monorepo_subdir=apps/map;
ingress:
  enabled: false
service:
  port: 3000
  type: ClusterIP
resources: {}
