secrets:
  create: true
  mapApiKey: ""
map:
  coreUrl: "http://galoy-oathkeeper-proxy.galoy-dev-galoy.svc.cluster.local:4455/graphql"
  otelExporterOtlpEndpoint: http://localhost:4318
  tracingServiceName: "map"
image:
  repository: us.gcr.io/galoy-org/galoy-map
  digest: "sha256:7224796568cd126f1a5a9059181bcd25fc8a3436824bd90e4fef1a3924975a91" # METADATA:: repository=https://github.com/blinkbitcoin/blink;commit_ref=a97546f;app=map;monorepo_subdir=apps/map;
ingress:
  enabled: false
service:
  port: 3000
  type: ClusterIP
resources: {}
