{{- if (index .Values "strimzi-kafka-operator").enabled -}}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: kafka
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: ephemeral
  resources:
    {{ toYaml (index .Values "strimzi-kafka-operator" "kafka" "resources") | nindent 4 }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    listeners:
      - name: plain
        port: 9092
        type: {{ index .Values "strimzi-kafka-operator" "kafka" "listener" "type" }}
        tls: false
    config:
      # https://github.com/strimzi/strimzi-kafka-operator/blob/main/documentation/api/io.strimzi.api.kafka.model.KafkaClusterSpec.adoc
      # https://github.com/strimzi/strimzi-kafka-operator/blob/main/documentation/modules/managing/con-broker-config-properties.adoc
      auto.create.topics.enable: false
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 1
      default.replication.factor: 3
      min.insync.replicas: 2
      log.retention.hours: 72 # 3 days
      log.segment.bytes: 100000000 # 100 MB
      log.retention.check.interval.ms: 300000 # 5 minutes
  entityOperator:
    userOperator: {}
{{- end -}}
