{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "blink-lnurl-server.fullname" . }}
  labels:
    app: {{ template "blink-lnurl-server.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  db-url: {{ .Values.secrets.dbUrl | b64enc | quote }}
  ssp-auth-seed: {{ .Values.secrets.sspAuthSeed | b64enc | quote }}
{{- if .Values.secrets.nsec }}
  nsec: {{ .Values.secrets.nsec | b64enc | quote }}
{{- end }}
{{- if .Values.secrets.caCert }}
  ca-cert: {{ .Values.secrets.caCert | b64enc | quote }}
{{- end }}
{{- end }}
