{{- if and .Values.enabled .Values.lit.uiPassword (not .Values.lit.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lightning-terminal.fullname" . }}-password
  labels:
    {{- include "lightning-terminal.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.lit.uiPassword | quote }}
{{- end }}

