load('ext://namespace', 'namespace_create')
load('ext://secret', 'secret_from_dict')
load('ext://helm_resource', 'helm_resource')
load('../common/Tiltfile', 'helm_release')

name_prefix = 'galoy-dev'
noncust_namespace = '{}-noncust'.format(name_prefix)
smoketest_namespace = '{}-smoketest'.format(name_prefix)

namespace_create(noncust_namespace)
namespace_create(smoketest_namespace)

local('helm repo add bitnami https://charts.bitnami.com/bitnami')

helm_resource(
  name='blink-lnurl-server-postgresql',
  chart='bitnami/postgresql',
  namespace=noncust_namespace,
  flags=[
    '--values=./postgresql-values.yml',
  ],
  labels='noncust'
)

k8s_yaml(secret_from_dict(
  name='blink-lnurl-server',
  namespace=noncust_namespace,
  inputs={
    'db-url': 'postgres://lnurl:lnurl@blink-lnurl-server-postgresql.{}.svc.cluster.local:5432/lnurl'.format(noncust_namespace),
    'ssp-auth-seed': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  }
))

helm_release(
  '../../charts/blink-lnurl-server',
  name='blink-lnurl-server',
  namespace=noncust_namespace,
  values=['./blink-lnurl-server-values.yml'],
)

k8s_resource(
  workload='blink-lnurl-server',
  labels='noncust',
  resource_deps=['blink-lnurl-server-postgresql'],
  port_forwards=8080,
)

k8s_yaml(secret_from_dict(
  name='blink-lnurl-server-smoketest',
  namespace=smoketest_namespace,
  inputs={
    'blink_lnurl_server_endpoint': 'blink-lnurl-server.{}.svc.cluster.local'.format(noncust_namespace),
    'blink_lnurl_server_port': '8080',
  }
))
