global:
  security:
    allowInsecureImages: true
secrets:
  create: true
  databaseUrl: ""
  redisPassword: ""
  jwtSecret: ""
  encryptionKey: ""
  networkEncryptionKey: ""
  blinkposApiKey: ""
  blinkposBtcWalletId: ""
  blinkWebhookSecret: ""
  citrusrateApiKey: ""
blinkTerminal:
  blinkApiUrl: "http://galoy-oathkeeper-proxy.galoy-dev-galoy.svc.cluster.local:4455/graphql"
  blinkEnvironment: "staging"
  redisHost: "localhost"
  redisPort: "6379"
  redisDb: "0"
  enableHybridStorage: "false"
  loglevel: "info"
  otelExporterOtlpEndpoint: http://localhost:4318
  tracingServiceName: "blink-terminal"
  citrusrateBaseUrl: "https://citrusrate-be.onrender.com"
image:
  repository: us.gcr.io/galoy-org/blink-terminal
  digest: "sha256:c6748f18df8f84abfdc1d973397a18e3513c05a3a6487adc67891a2d022ad539" # METADATA:: repository=https://github.com/blinkbitcoin/blink-terminal;commit_ref=cfde37b;app=blink-terminal;
psqlImage: "postgres:15"
ingress:
  enabled: false
service:
  port: 3000
  type: ClusterIP
postgresql:
  image:
    repository: bitnamilegacy/postgresql
  enabled: true
  auth:
    enablePostgresUser: false
    username: blink_terminal
    password: blink_terminal
    database: blink_terminal
resources: {}
