## The image is built with the Dockerfile in /images/kafka-connect
image:
  repository: us.gcr.io/galoy-org/kafka-connect
  digest: sha256:a2c8878cea8082d9c80e778a18c9481fde8b34b09d2be5f7a8cf00e5e88d5b66
  git_ref: 0fa5bcb
# Change to allow multiple kafka-connect instances
kafkaConnectInstanceName: kafka
## The pods from this namespace are allowed to access the Kafka Connect API
allowedNamespace: ""
## The contents of the secrets are mounted as a file to be used by the Kafka connectors running in the pod
## mounts to: /opt/kafka/external-configuration/<secretName>/<data.value>
secretMounts: []
resources: {}
