secrets:
  create: false

blinkLnurlServer:
  deploymentEnv: "staging"
  domains: "${service_host}:8080"
  scheme: "http"
  webhookDomain: "${service_host}:8080"
  logLevel: "debug"
  autoMigrate: "true"
