global:
  network: regtest

# Use the locally built backup image
backupImage:
  repository: lnd-backup
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 200m
    memory: 512Mi

terminationGracePeriodSeconds: 0

persistence:
  enabled: false

# Enable backup for testing
backup:
  enabled: true
  s3:
    enabled: true
    bucketName: "test-backup-bucket"
    region: "us-east-1"

configmap:
  customValues:
  - bitcoin.regtest=true
  - bitcoin.defaultchanconfs=0
  - noseedbackup=1
  - bitcoind.rpchost=bitcoind:18443
  - keysend-hold-time=2s
  - tlsextradomain=lnd1.galoy-dev-bitcoin.svc.cluster.local
