secrets:
  create: true
  dbUrl: ""
  sspAuthSeed: ""
  nsec: ""
  caCert: ""
blinkLnurlServer:
  address: "0.0.0.0:8080"
  autoMigrate: "true"
  deploymentEnv: "production"
  sparkEnabled: "true"
  blinkEnabled: "true"
  domains: "localhost:8080"
  callbackDomain: ""
  sparkNetwork: ""
  blinkGraphqlEndpoint: ""
  scheme: "https"
  webhookDomain: ""
  logLevel: "info"
  minSendable: "1000"
  maxSendable: "4000000000"
  webhookDeliveryTtlDays: "90"
  crlUrl: ""
  internalJwksUrl: ""
  internalJwksPath: ""
  internalJwtIssuer: ""
  internalJwtAudience: ""
image:
  repository: us.gcr.io/galoy-org/blink-lnurl-server
  digest: "sha256:18d193f564b4ae724df81e4514e620e1b2a9a9daa961d194e558620a755d3f40" # METADATA:: repository=https://github.com/blinkbitcoin/blink-lnurl-server;commit_ref=df4f59c;app=blink-lnurl-server;
ingress:
  enabled: false
  hosts: []
  rulesOverride: null
  extraTls: []
service:
  port: 8080
  type: ClusterIP
resources: {}
